var data = [
{
'day':30,
'month':1,
'year':2018,
'values': [
{'value':0,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':31,
'month':1,
'year':2018,
'values': [
{'value':0,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':1,
'month':2,
'year':2018,
'values': [
{'value':0,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':2,
'month':2,
'year':2018,
'values': [
{'value':0,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':3,
'month':2,
'year':2018,
'values': [
{'value':0,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':4,
'month':2,
'year':2018,
'values': [
{'value':0,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':5,
'month':2,
'year':2018,
'values': [
{'value':0,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':6,
'month':2,
'year':2018,
'values': [
{'value':0,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':7,
'month':2,
'year':2018,
'values': [
{'value':0,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':8,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':9,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':10,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':11,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':12,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':13,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':14,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':15,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':16,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':17,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':0,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':18,
'month':2,
'year':2018,
'values': [
{'value':1,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':19,
'month':2,
'year':2018,
'values': [
{'value':2,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':20,
'month':2,
'year':2018,
'values': [
{'value':4,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':21,
'month':2,
'year':2018,
'values': [
{'value':4,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':22,
'month':2,
'year':2018,
'values': [
{'value':4,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':23,
'month':2,
'year':2018,
'values': [
{'value':4,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':24,
'month':2,
'year':2018,
'values': [
{'value':4,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':25,
'month':2,
'year':2018,
'values': [
{'value':4,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':1,
'name':'YasirZardari'}
]
},{
'day':26,
'month':2,
'year':2018,
'values': [
{'value':4,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':27,
'month':2,
'year':2018,
'values': [
{'value':5,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':28,
'month':2,
'year':2018,
'values': [
{'value':5,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':1,
'month':3,
'year':2018,
'values': [
{'value':5,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':2,
'month':3,
'year':2018,
'values': [
{'value':5,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':1,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':3,
'month':3,
'year':2018,
'values': [
{'value':9,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':6,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':4,
'month':3,
'year':2018,
'values': [
{'value':9,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':6,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':0,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':5,
'month':3,
'year':2018,
'values': [
{'value':10,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':8,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':6,
'month':3,
'year':2018,
'values': [
{'value':13,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':8,
'name':'sloder75'}
,{'value':0,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':7,
'month':3,
'year':2018,
'values': [
{'value':13,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':8,
'name':'sloder75'}
,{'value':2,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':8,
'month':3,
'year':2018,
'values': [
{'value':13,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':8,
'name':'sloder75'}
,{'value':2,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':2,
'name':'YasirZardari'}
]
},{
'day':9,
'month':3,
'year':2018,
'values': [
{'value':13,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':11,
'name':'sloder75'}
,{'value':4,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':10,
'month':3,
'year':2018,
'values': [
{'value':15,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':11,
'name':'sloder75'}
,{'value':4,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':11,
'month':3,
'year':2018,
'values': [
{'value':15,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':11,
'name':'sloder75'}
,{'value':4,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':12,
'month':3,
'year':2018,
'values': [
{'value':15,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':11,
'name':'sloder75'}
,{'value':4,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':13,
'month':3,
'year':2018,
'values': [
{'value':16,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':11,
'name':'sloder75'}
,{'value':8,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':14,
'month':3,
'year':2018,
'values': [
{'value':16,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':11,
'name':'sloder75'}
,{'value':8,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':15,
'month':3,
'year':2018,
'values': [
{'value':16,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':11,
'name':'sloder75'}
,{'value':8,
'name':'arthursmel'}
,{'value':1,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':16,
'month':3,
'year':2018,
'values': [
{'value':18,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':14,
'name':'sloder75'}
,{'value':12,
'name':'arthursmel'}
,{'value':2,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':17,
'month':3,
'year':2018,
'values': [
{'value':18,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':14,
'name':'sloder75'}
,{'value':12,
'name':'arthursmel'}
,{'value':2,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':18,
'month':3,
'year':2018,
'values': [
{'value':18,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':14,
'name':'sloder75'}
,{'value':14,
'name':'arthursmel'}
,{'value':2,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':19,
'month':3,
'year':2018,
'values': [
{'value':18,
'name':'maximus1094'}
,{'value':0,
'name':'saphilli'}
,{'value':14,
'name':'sloder75'}
,{'value':14,
'name':'arthursmel'}
,{'value':2,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':20,
'month':3,
'year':2018,
'values': [
{'value':18,
'name':'maximus1094'}
,{'value':4,
'name':'saphilli'}
,{'value':14,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':2,
'name':'bharrisotcd'}
,{'value':3,
'name':'YasirZardari'}
]
},{
'day':21,
'month':3,
'year':2018,
'values': [
{'value':18,
'name':'maximus1094'}
,{'value':7,
'name':'saphilli'}
,{'value':14,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':2,
'name':'bharrisotcd'}
,{'value':4,
'name':'YasirZardari'}
]
},{
'day':22,
'month':3,
'year':2018,
'values': [
{'value':23,
'name':'maximus1094'}
,{'value':9,
'name':'saphilli'}
,{'value':20,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':4,
'name':'YasirZardari'}
]
},{
'day':23,
'month':3,
'year':2018,
'values': [
{'value':24,
'name':'maximus1094'}
,{'value':9,
'name':'saphilli'}
,{'value':24,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':4,
'name':'YasirZardari'}
]
},{
'day':24,
'month':3,
'year':2018,
'values': [
{'value':24,
'name':'maximus1094'}
,{'value':9,
'name':'saphilli'}
,{'value':25,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':4,
'name':'YasirZardari'}
]
},{
'day':25,
'month':3,
'year':2018,
'values': [
{'value':24,
'name':'maximus1094'}
,{'value':17,
'name':'saphilli'}
,{'value':25,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':4,
'name':'YasirZardari'}
]
},{
'day':26,
'month':3,
'year':2018,
'values': [
{'value':27,
'name':'maximus1094'}
,{'value':26,
'name':'saphilli'}
,{'value':25,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':4,
'name':'YasirZardari'}
]
},{
'day':27,
'month':3,
'year':2018,
'values': [
{'value':27,
'name':'maximus1094'}
,{'value':26,
'name':'saphilli'}
,{'value':25,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':4,
'name':'YasirZardari'}
]
},{
'day':28,
'month':3,
'year':2018,
'values': [
{'value':27,
'name':'maximus1094'}
,{'value':26,
'name':'saphilli'}
,{'value':25,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':4,
'name':'YasirZardari'}
]
},{
'day':29,
'month':3,
'year':2018,
'values': [
{'value':31,
'name':'maximus1094'}
,{'value':26,
'name':'saphilli'}
,{'value':25,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':7,
'name':'YasirZardari'}
]
},{
'day':30,
'month':3,
'year':2018,
'values': [
{'value':31,
'name':'maximus1094'}
,{'value':26,
'name':'saphilli'}
,{'value':25,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':7,
'name':'YasirZardari'}
]
},{
'day':31,
'month':3,
'year':2018,
'values': [
{'value':31,
'name':'maximus1094'}
,{'value':26,
'name':'saphilli'}
,{'value':26,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':7,
'name':'YasirZardari'}
]
},{
'day':1,
'month':4,
'year':2018,
'values': [
{'value':31,
'name':'maximus1094'}
,{'value':29,
'name':'saphilli'}
,{'value':26,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':4,
'name':'bharrisotcd'}
,{'value':7,
'name':'YasirZardari'}
]
},{
'day':2,
'month':4,
'year':2018,
'values': [
{'value':31,
'name':'maximus1094'}
,{'value':29,
'name':'saphilli'}
,{'value':26,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':8,
'name':'bharrisotcd'}
,{'value':7,
'name':'YasirZardari'}
]
},{
'day':3,
'month':4,
'year':2018,
'values': [
{'value':31,
'name':'maximus1094'}
,{'value':31,
'name':'saphilli'}
,{'value':28,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':8,
'name':'bharrisotcd'}
,{'value':10,
'name':'YasirZardari'}
]
},{
'day':4,
'month':4,
'year':2018,
'values': [
{'value':31,
'name':'maximus1094'}
,{'value':32,
'name':'saphilli'}
,{'value':28,
'name':'sloder75'}
,{'value':15,
'name':'arthursmel'}
,{'value':9,
'name':'bharrisotcd'}
,{'value':10,
'name':'YasirZardari'}
]
},{
'day':5,
'month':4,
'year':2018,
'values': [
{'value':35,
'name':'maximus1094'}
,{'value':32,
'name':'saphilli'}
,{'value':28,
'name':'sloder75'}
,{'value':20,
'name':'arthursmel'}
,{'value':11,
'name':'bharrisotcd'}
,{'value':10,
'name':'YasirZardari'}
]
},{
'day':6,
'month':4,
'year':2018,
'values': [
{'value':38,
'name':'maximus1094'}
,{'value':32,
'name':'saphilli'}
,{'value':28,
'name':'sloder75'}
,{'value':22,
'name':'arthursmel'}
,{'value':11,
'name':'bharrisotcd'}
,{'value':11,
'name':'YasirZardari'}
]
}]
